@startuml
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([not all ingredients' levels are already at zero])
    :Find the ingredient(s) that has non-zero ingredient level in IngredientBook
    and replace them with new ingredient objects that has the same ingredient name,
    and zero ingredient level(s);
    :Save the updated IngredientBook in storage;
else ([else])
    : Show a message stating that all ingredient levels are already at zero;
endif
stop
@enduml
