@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title Initial content

package System {

    object IngredientBook {
    {field} uniqueIngredientList : （Milk, Amount:0 Pearl, Amount:0 Boba, Amount:0 Oolong_Tea, Amount:0 Brown_Sugar, Amount:0）
    }
}

class Pointer as "Model" #FFFFF
Pointer -up-> IngredientBook
note right on link: Other books omitted.
@end
