@startuml
start
:User executes i-set/i-set-default/i-set-all command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command changed IngredientBook])
    :Change uniqueIngredientList
    according to user inputs;
    :Replace ingredientBook with a new one
    with the updated uniqueIngredientList;
else ([else])
    :Throw NoChangeIngredient Exception;

endif
stop
@enduml
